my_robot:
  dt: 0.005
  decimation: 4

# 关节限幅
joint_limits:
  dof_hip_pos_min: -1.571
  dof_hip_pos_max: 1.571

  dof_thigh_pos_min: -2.356
  dof_thigh_pos_max: 2.356

  dof_calf_pos_min: -2.670
  dof_calf_pos_max: -0.5

  vel_max: 30.0
  torque_max: 23.7

# 关节角度与电机的映射
joint_hardware_params:
  FL_hip:
    motor_idx: 0       
    direction: 1.0        
  FL_thigh:
    motor_idx: 1
    direction: 1.0
  FL_calf:
    motor_idx: 2
    direction: 1.0

  FR_hip:
    motor_idx: 3
    direction: 1.0
  FR_thigh:
    motor_idx: 4
    direction: -1.0
  FR_calf:
    motor_idx: 5
    direction: -1.0

  RL_hip:
    motor_idx: 6
    direction: -1.0
  RL_thigh:
    motor_idx: 7
    direction: 1.0
  RL_calf:
    motor_idx: 8
    direction: 1.0

  RR_hip:
    motor_idx: 9
    direction: -1.0
  RR_thigh:
    motor_idx: 10
    direction: -1.0
  RR_calf:
    motor_idx: 11
    direction: -1.0

joint_init_pos:
  FL_hip: 0.617
  FL_thigh: 1.18
  FL_calf: -2.67

  FR_hip: -0.617
  FR_thigh: 1.18
  FR_calf: -2.67

  RL_hip: 0.617
  RL_thigh: 1.18
  RL_calf: -2.67

  RR_hip: -0.617
  RR_thigh: 1.18
  RR_calf: -2.67
